### ISSUE TITLE
Invalid CURL arguments on AWS

### ISSUE THREAD

**Issue by prashanth5192** [Accelize/gunzip#1]
Not sure if this is a minor or major issue, happening in case of configured AWS while running an example client.

[root@fpga-study gunzip]# python run_example.py
1- Creating Accelerator...
2- Creating and Initializing Instance...
3- Processing
Instance 'i-0c1fd956dd8367b00' has been terminated
Traceback (most recent call last):
  File "run_example.py", line 25, in <module>
    myaccel.process(file_in="samples/sample_1_1MB.txt.gz", file_out="results/sample_1_1MB.txt")
  File "/usr/lib/python2.7/site-packages/apyfal/__init__.py", line 225, in process
    info_dict=info_dict or _enable_logger, **parameters)
  File "/usr/lib/python2.7/site-packages/apyfal/client/__init__.py", line 239, in process
    response = self._process(file_in, file_out, parameters)
  File "/usr/lib/python2.7/site-packages/apyfal/client/rest/__init__.py", line 322, in _process
    file_in)
  File "/usr/lib/python2.7/site-packages/apyfal/client/rest/__init__.py", line 268, in _process_curl
    curl.setopt(_pycurl.WRITEDATA, write_buffer)
TypeError: invalid arguments to setopt

**Comment by xlz-jgoutin** [comment]
Hello,

After a quick look, it seem `WRITEDATA` needs at least PycURL >= 7.19.3.

If your version is older 7.19.3, please try to upgrade PycURL and retry.
Else, I will look to reproduce this.

Apyfal was actually developed and tested with last dependencies version. I planned to check dependencies versions and set limit in setup to avoid this kind of issue.

In wait, I recommend to use a updated Python environment (Eventually trough a virtual env).

**Comment by prashanth5192** [comment]
Yes, updating the pipcurl solves the issue. I was able to run and get the results. 
But even though I set the stop_mode=keep in the config file, the inference is still terminated,
Thank you again for your quick responses. I appreciate it.

**Comment by xlz-jgoutin** [comment]
The `stop_mode=keep` in configuration file that don't work is a known issue that I fixed in the development version.

As workaround, you can pass `stop_mode` directly in the Python code of `run_example.py`:
```python
with Accelerator(accelerator='cast_gunzip', stop_mode="keep") as myaccel:
```
